// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ćwiczenie4_KamilWolak.DbConnection;

#nullable disable

namespace Ćwiczenie4_KamilWolak.Migrations
{
    [DbContext(typeof(CurrencyDbContext))]
    partial class CurrencyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Ćwiczenie4_KamilWolak.Entities.ExchangeTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("No")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Table")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExchangeTables");
                });

            modelBuilder.Entity("Ćwiczenie4_KamilWolak.Entities.Rate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExchangeTableId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Mid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeTableId");

                    b.ToTable("Rates");
                });

            modelBuilder.Entity("Ćwiczenie4_KamilWolak.Entities.Rate", b =>
                {
                    b.HasOne("Ćwiczenie4_KamilWolak.Entities.ExchangeTable", "ExchangeTable")
                        .WithMany("Rates")
                        .HasForeignKey("ExchangeTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExchangeTable");
                });

            modelBuilder.Entity("Ćwiczenie4_KamilWolak.Entities.ExchangeTable", b =>
                {
                    b.Navigation("Rates");
                });
#pragma warning restore 612, 618
        }
    }
}
